"""Small quantum-mechanics reference utilities.

``quantum_phase_step`` keeps the historical Clarus API

    psi_{k+1} = exp(-i E dt) psi_k

but this is only the global phase generated by ``H = E I``.  It cannot change
Born probabilities, relative phases, or populations and must not be read as a
general quantum simulation.

The Hamiltonian, density-matrix, Born, and Lindblad helpers below are standard
QM baselines.  They intentionally make no claim about a CE-specific quantum
effect.  Wick rotation remains the legacy bridge to real relaxation.
"""

from __future__ import annotations

import math
from dataclasses import dataclass
from numbers import Real
from typing import Sequence

import torch

ALPHA_B_DEFAULT = math.exp(1.0 / 3.0) * (math.pi ** (1.0 / 3.0))
ELEMENTARY_CHARGE_C = 1.602176634e-19
PLANCK_CONSTANT_J_S = 6.62607015e-34
HBAR_J_S = PLANCK_CONSTANT_J_S / (2.0 * math.pi)
BOLTZMANN_CONSTANT_J_K = 1.380649e-23
MEV_TO_J = 1.0e6 * ELEMENTARY_CHARGE_C

# A numerical reference requested for comparison, not evidence for a CE field.
REFERENCE_SCALAR_MASS_MEV = 29.64757


def _complex_dtype(*tensors: torch.Tensor) -> torch.dtype:
    """Return a matrix-exponential-safe complex dtype for the inputs."""
    if any(t.dtype in (torch.float64, torch.complex128) for t in tensors):
        return torch.complex128
    return torch.complex64


def _as_complex(
    value: torch.Tensor,
    *,
    dtype: torch.dtype | None = None,
    device: torch.device | None = None,
) -> torch.Tensor:
    if not isinstance(value, torch.Tensor):
        raise TypeError("quantum states and operators must be torch tensors")
    target_dtype = dtype or _complex_dtype(value)
    target_device = device or value.device
    return value.to(device=target_device, dtype=target_dtype)


def _adjoint(value: torch.Tensor) -> torch.Tensor:
    return value.conj().transpose(-2, -1)


def _validate_square(value: torch.Tensor, *, name: str) -> None:
    if value.ndim != 2 or value.shape[0] != value.shape[1]:
        raise ValueError(f"{name} must be a square matrix")


def _validate_hermitian(
    value: torch.Tensor,
    *,
    name: str,
    atol: float = 1e-7,
) -> None:
    _validate_square(value, name=name)
    if not torch.allclose(value, _adjoint(value), atol=atol, rtol=atol):
        raise ValueError(f"{name} must be Hermitian")


def _finite_real(value: Real, *, name: str) -> float:
    if isinstance(value, bool) or not isinstance(value, Real):
        raise TypeError(f"{name} must be a real number")
    result = float(value)
    if not math.isfinite(result):
        raise ValueError(f"{name} must be finite")
    return result


def _nonnegative_real(value: Real, *, name: str) -> float:
    result = _finite_real(value, name=name)
    if result < 0.0:
        raise ValueError(f"{name} must be nonnegative")
    return result


def jacobi_rayleigh_scalar(
    jacobi_operator: torch.Tensor,
    probe: torch.Tensor,
    *,
    hermitian_atol: float = 1e-7,
) -> torch.Tensor:
    """Read a scalar from a supplied Hermitian Hessian/Jacobi operator.

    The readout is the scale-invariant Rayleigh quotient

        Phi_eff(v) = <v, J v> / <v, v>.

    ``J`` and the nonzero probe are external physical/model inputs.  This
    helper does not identify an independent scalar field with curvature
    ``R``, nor does it establish that such a field exists.
    """
    if not isinstance(jacobi_operator, torch.Tensor):
        raise TypeError("jacobi_operator must be a torch tensor")
    if not isinstance(probe, torch.Tensor):
        raise TypeError("probe must be a torch tensor")
    if probe.ndim != 1:
        raise ValueError("probe must be a one-dimensional vector")
    tolerance = _nonnegative_real(hermitian_atol, name="hermitian_atol")

    dtype = _complex_dtype(jacobi_operator, probe)
    operator_complex = _as_complex(jacobi_operator, dtype=dtype)
    probe_complex = _as_complex(
        probe,
        dtype=dtype,
        device=operator_complex.device,
    )
    if not bool(torch.isfinite(operator_complex).all().item()):
        raise ValueError("jacobi_operator must contain only finite values")
    if not bool(torch.isfinite(probe_complex).all().item()):
        raise ValueError("probe must contain only finite values")
    _validate_hermitian(
        operator_complex,
        name="jacobi_operator",
        atol=tolerance,
    )
    if operator_complex.shape[0] != probe_complex.shape[0]:
        raise ValueError("jacobi_operator dimension must match probe")

    norm_sq = torch.vdot(probe_complex, probe_complex).real
    if float(norm_sq.item()) <= 0.0:
        raise ValueError("probe must have nonzero norm")
    quotient = torch.vdot(
        probe_complex,
        operator_complex @ probe_complex,
    ) / norm_sq
    return quotient.real


@dataclass(frozen=True)
class ScalarFieldMassGap:
    """Unit-safe rest-energy/gap conversion for an independent scalar field.

    The canonical value is an energy in MeV.  Angular gap and ordinary
    frequency use ``E = hbar * omega = h * f`` with exact SI constants.  This
    container supplies no mass measurement or field-identification evidence.
    """

    mass_energy_mev: float

    def __post_init__(self) -> None:
        value = _nonnegative_real(
            self.mass_energy_mev,
            name="mass_energy_mev",
        )
        object.__setattr__(self, "mass_energy_mev", value)

    @property
    def energy_joule(self) -> float:
        """Return the mass energy in joules."""
        return self.mass_energy_mev * MEV_TO_J

    @property
    def angular_gap_s_inv(self) -> float:
        """Return ``omega = E / hbar`` in inverse seconds."""
        return self.energy_joule / HBAR_J_S

    @property
    def frequency_hz(self) -> float:
        """Return ``f = E / h`` in cycles per second (Hz)."""
        return self.energy_joule / PLANCK_CONSTANT_J_S

    @classmethod
    def from_angular_gap_s_inv(
        cls,
        angular_gap_s_inv: Real,
    ) -> ScalarFieldMassGap:
        """Construct from a nonnegative angular gap in inverse seconds."""
        omega = _nonnegative_real(
            angular_gap_s_inv,
            name="angular_gap_s_inv",
        )
        return cls(omega * HBAR_J_S / MEV_TO_J)

    @classmethod
    def from_frequency_hz(cls, frequency_hz: Real) -> ScalarFieldMassGap:
        """Construct from a nonnegative ordinary frequency in Hz."""
        frequency = _nonnegative_real(frequency_hz, name="frequency_hz")
        return cls(frequency * PLANCK_CONSTANT_J_S / MEV_TO_J)


@dataclass(frozen=True)
class IndependentScalarFieldAction:
    """Natural-unit parameters for an independent real scalar field.

    The fixed convention is the mostly-minus metric and

        S_phi = integral sqrt(-g) [
            1/2 (nabla phi)^2
            - 1/2 (m^2 + xi R) phi^2
            - lambda phi^4 / 4!
        ].

    Hence ``box(phi) + local_eom_term(phi, R) = 0``.  The curvature convention
    is ``R^rho_{ sigma mu nu} = d_mu Gamma^rho_{nu sigma}
    - d_nu Gamma^rho_{mu sigma} + ...`` and
    ``R_{sigma nu} = R^rho_{ sigma rho nu}``.  ``mass_squared``, ``R``, and
    the field amplitude must be supplied in one consistent natural-unit
    convention.  In particular, ``phi`` remains an independent field: this
    record never identifies it with the Ricci scalar.

    For this quartic truncation the constructor enforces a bounded *bare
    ``R=0``* large-field potential: ``lambda >= 0``, and a negative
    ``mass_squared`` is permitted only when ``lambda > 0`` supplies the
    stabilizing quartic term.  A supplied curvature can change the effective
    quadratic coefficient; use :meth:`potential_is_bounded_below_at_curvature`
    for that separate gate.
    """

    mass_squared: float
    curvature_coupling: float = 0.0
    quartic_coupling: float = 0.0

    def __post_init__(self) -> None:
        mass_squared = _finite_real(
            self.mass_squared,
            name="mass_squared",
        )
        curvature_coupling = _finite_real(
            self.curvature_coupling,
            name="curvature_coupling",
        )
        quartic_coupling = _nonnegative_real(
            self.quartic_coupling,
            name="quartic_coupling",
        )
        if mass_squared < 0.0 and quartic_coupling == 0.0:
            raise ValueError(
                "negative mass_squared requires positive quartic_coupling "
                "for this bounded-potential policy",
            )
        object.__setattr__(self, "mass_squared", mass_squared)
        object.__setattr__(self, "curvature_coupling", curvature_coupling)
        object.__setattr__(self, "quartic_coupling", quartic_coupling)

    def potential_density(self, field_value: Real, ricci_scalar: Real) -> float:
        """Return ``V(phi, R)`` in the caller's consistent natural units."""
        field = _finite_real(field_value, name="field_value")
        curvature = _finite_real(ricci_scalar, name="ricci_scalar")
        effective_mass_squared = (
            self.mass_squared + self.curvature_coupling * curvature
        )
        return (
            0.5 * effective_mass_squared * field * field
            + self.quartic_coupling * field**4 / math.factorial(4)
        )

    def local_eom_term(self, field_value: Real, ricci_scalar: Real) -> float:
        """Return ``(m^2 + xi R) phi + lambda phi^3 / 3!``."""
        field = _finite_real(field_value, name="field_value")
        curvature = _finite_real(ricci_scalar, name="ricci_scalar")
        return (
            (self.mass_squared + self.curvature_coupling * curvature) * field
            + self.quartic_coupling * field**3 / math.factorial(3)
        )

    def potential_is_bounded_below_at_curvature(
        self,
        ricci_scalar: Real,
    ) -> bool:
        """Check boundedness of this quartic potential at fixed curvature."""
        curvature = _finite_real(ricci_scalar, name="ricci_scalar")
        if self.quartic_coupling > 0.0:
            return True
        effective_mass_squared = (
            self.mass_squared + self.curvature_coupling * curvature
        )
        return effective_mass_squared >= 0.0

    def phi_zero_minkowski_angular_frequency_squared(
        self,
        spatial_wavenumber: Real,
    ) -> float:
        """Return ``omega^2=|k|^2+m^2`` linearized about ``phi=0``.

        This natural-unit, flat-space check fixes the mostly-minus kinetic
        sign.  When ``mass_squared < 0``, ``phi=0`` is an unstable stationary
        point rather than the broken-symmetry vacuum, and a negative result is
        reported without clipping.
        """
        wavenumber = _nonnegative_real(
            spatial_wavenumber,
            name="spatial_wavenumber",
        )
        return wavenumber * wavenumber + self.mass_squared


def gksl_rate_from_spectral_density(
    coupling: Real,
    spectral_density: Real,
) -> float:
    """Return the reduced-frequency Born-Markov input ``gamma = g**2 J``.

    The caller must already use an interaction-generator convention such as
    ``H_int / hbar = g A tensor O`` and a reduced spectral density whose
    product ``g**2 J`` is in inverse seconds.  A raw SI correlator transform
    for a dimensionless bath operator has units of seconds and must instead
    be converted with :func:`gksl_rate_from_si_correlation_spectrum`, which
    includes ``1 / hbar**2``.  No universal spectral shape, bath state, or
    CE-specific interaction is assumed.
    """
    coupling_value = _finite_real(coupling, name="coupling")
    density_value = _nonnegative_real(
        spectral_density,
        name="spectral_density",
    )
    rate = coupling_value * coupling_value * density_value
    if not math.isfinite(rate):
        raise ValueError("g**2 times spectral_density must be finite")
    return rate


def gksl_rate_from_si_correlation_spectrum(
    coupling_energy_joule: Real,
    correlation_spectrum_seconds: Real,
) -> float:
    """Return ``gamma=(g_J/hbar)^2 G`` for an SI Hamiltonian coupling.

    This convention assumes ``H_int = g_J A tensor O`` with dimensionless
    ``A`` and ``O``.  Then

        G(omega) = integral dt exp(+i omega t) <O(t) O(0)>

    has units of seconds and ``gamma`` has units of inverse seconds.  This
    explicit converter prevents a raw correlator spectrum from being confused
    with the reduced rate-density convention used by
    :func:`gksl_rate_from_spectral_density`.
    """
    coupling_energy = _finite_real(
        coupling_energy_joule,
        name="coupling_energy_joule",
    )
    spectrum = _nonnegative_real(
        correlation_spectrum_seconds,
        name="correlation_spectrum_seconds",
    )
    rate = (coupling_energy / HBAR_J_S) ** 2 * spectrum
    if not math.isfinite(rate):
        raise ValueError(
            "(coupling_energy_joule / hbar)**2 times "
            "correlation_spectrum_seconds must be finite",
        )
    return rate


def correlator_fourier_component(
    times_s: torch.Tensor,
    correlator: torch.Tensor,
    angular_frequency_s_inv: Real,
) -> torch.Tensor:
    """Numerically evaluate an unsymmetrized correlator Fourier component.

    The convention is

        G(omega) = integral dt exp(+i omega t) <O(t) O(0)>.

    The caller supplies a strictly increasing time grid spanning negative and
    positive times and the corresponding correlator.  Its units are
    ``[correlator] * seconds``.  The returned finite-window trapezoid integral
    is generally complex; windowing, aliasing, positivity, stationarity and
    KMS are separate physical gates, not values silently imposed by this
    numerical transform.
    """
    if not isinstance(times_s, torch.Tensor):
        raise TypeError("times_s must be a torch tensor")
    if not isinstance(correlator, torch.Tensor):
        raise TypeError("correlator must be a torch tensor")
    if times_s.ndim != 1 or correlator.ndim != 1:
        raise ValueError("times_s and correlator must be one-dimensional")
    if times_s.numel() < 2:
        raise ValueError("times_s must contain at least two samples")
    if times_s.shape != correlator.shape:
        raise ValueError("times_s and correlator must have matching shapes")
    if times_s.is_complex():
        raise ValueError("times_s must be real")
    if not bool(torch.isfinite(times_s).all().item()):
        raise ValueError("times_s must contain only finite values")
    if not bool(torch.isfinite(correlator).all().item()):
        raise ValueError("correlator must contain only finite values")
    if not bool((times_s[1:] > times_s[:-1]).all().item()):
        raise ValueError("times_s must be strictly increasing")
    if not (
        float(times_s[0].item()) < 0.0
        and float(times_s[-1].item()) > 0.0
    ):
        raise ValueError("times_s must span both negative and positive times")
    frequency = _finite_real(
        angular_frequency_s_inv,
        name="angular_frequency_s_inv",
    )

    dtype = _complex_dtype(times_s, correlator)
    real_dtype = torch.float64 if dtype == torch.complex128 else torch.float32
    time_values = times_s.to(dtype=real_dtype)
    correlation_values = _as_complex(
        correlator,
        dtype=dtype,
        device=time_values.device,
    )
    phase = torch.exp(1j * frequency * time_values).to(dtype=dtype)
    return torch.trapezoid(correlation_values * phase, time_values)


def kms_detailed_balance_factor(
    angular_frequency_s_inv: Real,
    temperature_kelvin: Real,
) -> float:
    """Return ``exp[-hbar*omega/(k_B*T)]`` for ``omega >= 0`` and ``T > 0``."""
    frequency = _nonnegative_real(
        angular_frequency_s_inv,
        name="angular_frequency_s_inv",
    )
    temperature = _finite_real(temperature_kelvin, name="temperature_kelvin")
    if temperature <= 0.0:
        raise ValueError("temperature_kelvin must be positive")
    exponent = -HBAR_J_S * frequency / (BOLTZMANN_CONSTANT_J_K * temperature)
    return math.exp(exponent)


def check_scalar_kms_spectral_pair(
    positive_frequency_spectral_density: Real,
    negative_frequency_spectral_density: Real,
    angular_frequency_s_inv: Real,
    temperature_kelvin: Real,
    *,
    atol: Real = 0.0,
    rtol: Real = 1e-9,
) -> bool:
    """Check scalar Hermitian-bath KMS detailed balance.

    The convention is a stationary equilibrium correlator of one Hermitian
    operator, ``C(t)=<O(t)O(0)>`` and
    ``G(omega)=integral dt exp(+i omega t) C(t)``.  It then checks
    ``G(-omega)=exp(-beta*hbar*omega)G(+omega)`` for ``omega >= 0``.
    Multichannel or non-Hermitian baths require an indexed matrix KMS relation
    with the appropriate operator ordering and are outside this scalar gate.

    Both supplied values must be finite and nonnegative.  ``atol`` has the
    same units as the spectra and defaults to zero so an absent expected mode
    cannot pass merely because both numbers are small.  This gate checks a
    caller-provided bath spectrum; it does not derive it from the scalar
    action.
    """
    positive = _nonnegative_real(
        positive_frequency_spectral_density,
        name="positive_frequency_spectral_density",
    )
    negative = _nonnegative_real(
        negative_frequency_spectral_density,
        name="negative_frequency_spectral_density",
    )
    absolute_tolerance = _nonnegative_real(atol, name="atol")
    relative_tolerance = _nonnegative_real(rtol, name="rtol")
    expected_negative = positive * kms_detailed_balance_factor(
        angular_frequency_s_inv,
        temperature_kelvin,
    )
    return math.isclose(
        negative,
        expected_negative,
        abs_tol=absolute_tolerance,
        rel_tol=relative_tolerance,
    )


@dataclass(frozen=True)
class ThermalTransitionRates:
    """Downward/upward GKSL rates completed with the KMS relation."""

    downward_s_inv: float
    upward_s_inv: float
    detailed_balance_factor: float

    def __post_init__(self) -> None:
        downward = _nonnegative_real(
            self.downward_s_inv,
            name="downward_s_inv",
        )
        upward = _nonnegative_real(
            self.upward_s_inv,
            name="upward_s_inv",
        )
        factor = _finite_real(
            self.detailed_balance_factor,
            name="detailed_balance_factor",
        )
        if not 0.0 <= factor <= 1.0:
            raise ValueError("detailed_balance_factor must lie in [0, 1]")
        if not math.isclose(
            upward,
            downward * factor,
            rel_tol=1e-12,
            abs_tol=0.0,
        ):
            raise ValueError(
                "upward_s_inv must equal downward_s_inv times "
                "detailed_balance_factor",
            )
        object.__setattr__(self, "downward_s_inv", downward)
        object.__setattr__(self, "upward_s_inv", upward)
        object.__setattr__(self, "detailed_balance_factor", factor)


def kms_thermal_transition_rates_from_reduced_spectrum(
    coupling: Real,
    positive_frequency_reduced_spectrum: Real,
    angular_frequency_s_inv: Real,
    temperature_kelvin: Real,
) -> ThermalTransitionRates:
    """Complete reduced-frequency downward/upward rates using scalar KMS.

    ``positive_frequency_reduced_spectrum`` follows the explicit
    interaction-generator convention of
    :func:`gksl_rate_from_spectral_density`: after multiplication by ``g^2``
    it is in inverse seconds.  It is not an arbitrary SI correlator output.

    For the eigenoperator convention
    ``[H_S, A(omega)] = -hbar*omega*A(omega)`` and ``omega > 0``,
    the positive-frequency spectrum drives downward emission and the negative-
    frequency spectrum drives upward absorption.  The latter is imposed by
    scalar Hermitian-bath KMS here, so this is a reference completion rather
    than evidence that a proposed CE bath is thermal.
    """
    downward = gksl_rate_from_spectral_density(
        coupling,
        positive_frequency_reduced_spectrum,
    )
    factor = kms_detailed_balance_factor(
        angular_frequency_s_inv,
        temperature_kelvin,
    )
    upward = downward * factor
    return ThermalTransitionRates(
        downward_s_inv=downward,
        upward_s_inv=upward,
        detailed_balance_factor=factor,
    )


@dataclass(frozen=True)
class KossakowskiJumpDecomposition:
    """Auditable eigendecomposition of a supplied Kossakowski matrix."""

    jump_operators: tuple[torch.Tensor, ...]
    rates: tuple[float, ...]
    represented_matrix: torch.Tensor
    input_residual_frobenius: float
    minimum_input_eigenvalue: float
    psd_acceptance_tolerance: float
    mode_cutoff: float
    hermitian_atol: float
    hermitian_rtol: float


def validate_kossakowski_matrix(
    kossakowski_matrix: torch.Tensor,
    *,
    psd_atol: Real = 0.0,
    psd_rtol: Real = 0.0,
    hermitian_atol: Real = 1e-12,
    hermitian_rtol: Real = 0.0,
) -> torch.Tensor:
    """Return a Hermitianized copy after a declared PSD-tolerance gate.

    The default PSD tolerance is strict.  With nonzero ``psd_atol`` or
    ``psd_rtol``, eigenvalues down to
    ``-(psd_atol + psd_rtol * spectral_scale)`` are accepted as numerical
    uncertainty.  This validator does not silently clip them; the jump
    decomposition exposes any later projection through an explicit residual.
    """
    if not isinstance(kossakowski_matrix, torch.Tensor):
        raise TypeError("kossakowski_matrix must be a torch tensor")
    absolute_tolerance = _nonnegative_real(psd_atol, name="psd_atol")
    relative_tolerance = _nonnegative_real(psd_rtol, name="psd_rtol")
    hermitian_tolerance = _nonnegative_real(
        hermitian_atol,
        name="hermitian_atol",
    )
    hermitian_relative_tolerance = _nonnegative_real(
        hermitian_rtol,
        name="hermitian_rtol",
    )
    matrix = _as_complex(kossakowski_matrix)
    if matrix.ndim != 2 or matrix.shape[0] == 0:
        raise ValueError("kossakowski_matrix must be a nonempty square matrix")
    if not bool(torch.isfinite(matrix).all().item()):
        raise ValueError("kossakowski_matrix must contain only finite values")
    _validate_square(matrix, name="kossakowski_matrix")
    if not torch.allclose(
        matrix,
        _adjoint(matrix),
        atol=hermitian_tolerance,
        rtol=hermitian_relative_tolerance,
    ):
        raise ValueError("kossakowski_matrix must be Hermitian")
    matrix = 0.5 * (matrix + _adjoint(matrix))
    eigenvalues = torch.linalg.eigvalsh(matrix).real
    spectral_scale = float(eigenvalues.abs().max().item())
    tolerance = absolute_tolerance + relative_tolerance * spectral_scale
    if float(eigenvalues.min().item()) < -tolerance:
        raise ValueError("kossakowski_matrix must be positive semidefinite")
    return matrix


def kossakowski_jump_decomposition(
    operator_basis: Sequence[torch.Tensor],
    kossakowski_matrix: torch.Tensor,
    *,
    psd_atol: Real = 0.0,
    psd_rtol: Real = 0.0,
    mode_cutoff: Real = 0.0,
    hermitian_atol: Real = 1e-12,
    hermitian_rtol: Real = 0.0,
) -> KossakowskiJumpDecomposition:
    """Represent a Kossakowski matrix as Lindblad jumps with audited residual.

    For basis operators ``F_a`` and coefficients ``C_ab``, this reproduces

        sum_ab C_ab [F_a rho F_b^dagger
                     - 1/2 {F_b^dagger F_a, rho}].

    Strict PSD validation and no positive-mode cutoff are the defaults.
    If a caller explicitly permits a small negative eigenvalue, it is projected
    to zero; if ``mode_cutoff > 0``, positive modes at or below that cutoff are
    also omitted.  ``represented_matrix`` is exactly the matrix represented by
    the returned jumps/rates, while ``input_residual_frobenius`` reports the
    total Hermitianization/projection/truncation change.  Thus the function
    never claims to reproduce a modified input silently.

    The matrix and basis are external inputs.  Their accepted positivity
    closes a finite-dimensional GKSL reference form but does not connect the
    scalar KMS pair to an arbitrary multichannel bath, nor supply a CE
    interaction, correlator, or weak-coupling/secular validity argument.
    """
    basis = tuple(operator_basis)
    if not basis:
        raise ValueError("operator_basis must contain at least one operator")
    for operator in basis:
        if not isinstance(operator, torch.Tensor):
            raise TypeError("operator_basis entries must be torch tensors")
        _validate_square(operator, name="operator_basis entry")
        if not bool(torch.isfinite(operator).all().item()):
            raise ValueError("operator_basis entries must contain only finite values")
    dimension = basis[0].shape[0]
    if any(operator.shape != (dimension, dimension) for operator in basis):
        raise ValueError("operator_basis entries must have matching shapes")

    absolute_tolerance = _nonnegative_real(psd_atol, name="psd_atol")
    relative_tolerance = _nonnegative_real(psd_rtol, name="psd_rtol")
    cutoff = _nonnegative_real(mode_cutoff, name="mode_cutoff")
    hermitian_absolute_tolerance = _nonnegative_real(
        hermitian_atol,
        name="hermitian_atol",
    )
    hermitian_relative_tolerance = _nonnegative_real(
        hermitian_rtol,
        name="hermitian_rtol",
    )
    input_matrix = _as_complex(kossakowski_matrix)
    matrix = validate_kossakowski_matrix(
        kossakowski_matrix,
        psd_atol=absolute_tolerance,
        psd_rtol=relative_tolerance,
        hermitian_atol=hermitian_absolute_tolerance,
        hermitian_rtol=hermitian_relative_tolerance,
    )
    if matrix.shape != (len(basis), len(basis)):
        raise ValueError(
            "kossakowski_matrix dimension must match operator_basis",
        )

    dtype = _complex_dtype(matrix, *basis)
    device = basis[0].device
    matrix = matrix.to(device=device, dtype=dtype)
    complex_basis = tuple(
        _as_complex(operator, dtype=dtype, device=device)
        for operator in basis
    )
    eigenvalues, eigenvectors = torch.linalg.eigh(matrix)
    spectral_scale = float(eigenvalues.real.abs().max().item())
    acceptance_tolerance = (
        absolute_tolerance + relative_tolerance * spectral_scale
    )
    represented_eigenvalues = torch.zeros_like(eigenvalues.real)
    jumps: list[torch.Tensor] = []
    rates: list[float] = []
    for index, eigenvalue in enumerate(eigenvalues):
        rate = max(float(eigenvalue.real.item()), 0.0)
        if rate <= cutoff:
            continue
        represented_eigenvalues[index] = rate
        jump = torch.zeros_like(complex_basis[0])
        for basis_index, operator in enumerate(complex_basis):
            jump = jump + eigenvectors[basis_index, index] * operator
        jumps.append(jump)
        rates.append(rate)
    represented_matrix = (
        eigenvectors
        @ torch.diag(represented_eigenvalues.to(dtype=dtype))
        @ _adjoint(eigenvectors)
    )
    input_on_device = input_matrix.to(device=device, dtype=dtype)
    residual = float(
        torch.linalg.matrix_norm(
            input_on_device - represented_matrix,
            ord="fro",
        ).real.item()
    )
    return KossakowskiJumpDecomposition(
        jump_operators=tuple(jumps),
        rates=tuple(rates),
        represented_matrix=represented_matrix,
        input_residual_frobenius=residual,
        minimum_input_eigenvalue=float(eigenvalues.real.min().item()),
        psd_acceptance_tolerance=acceptance_tolerance,
        mode_cutoff=cutoff,
        hermitian_atol=hermitian_absolute_tolerance,
        hermitian_rtol=hermitian_relative_tolerance,
    )


def quantum_phase_step(
    psi: torch.Tensor,
    energy: float,
    dt: float = 0.01,
) -> torch.Tensor:
    """Apply the legacy scalar-energy global-phase toy.

    This is exactly the special Hamiltonian ``H = energy * I``.  It preserves
    the historical API, but it is not a general Schrödinger step: every
    amplitude receives the same phase.
    """
    dtype = _complex_dtype(psi)
    psi = _as_complex(psi, dtype=dtype)
    real_dtype = torch.float64 if dtype == torch.complex128 else torch.float32
    phase = torch.as_tensor(
        -float(energy) * float(dt),
        device=psi.device,
        dtype=real_dtype,
    )
    rotation = torch.complex(torch.cos(phase), torch.sin(phase))
    return psi * rotation


def unitary_step(
    psi: torch.Tensor,
    hamiltonian: torch.Tensor,
    dt: float,
    *,
    hbar: float = 1.0,
    hermitian_atol: float = 1e-7,
) -> torch.Tensor:
    """Evolve a state vector with ``exp(-i H dt / hbar)``.

    This is the standard finite-dimensional Schrödinger reference step for a
    time-independent Hermitian Hamiltonian.
    """
    if psi.ndim != 1:
        raise ValueError("psi must be a one-dimensional state vector")
    if not math.isfinite(float(dt)):
        raise ValueError("dt must be finite")
    if not math.isfinite(float(hbar)) or hbar <= 0.0:
        raise ValueError("hbar must be finite and positive")

    dtype = _complex_dtype(psi, hamiltonian)
    psi_complex = _as_complex(psi, dtype=dtype)
    h_complex = _as_complex(
        hamiltonian,
        dtype=dtype,
        device=psi_complex.device,
    )
    _validate_hermitian(
        h_complex,
        name="hamiltonian",
        atol=hermitian_atol,
    )
    if h_complex.shape[0] != psi_complex.shape[0]:
        raise ValueError("hamiltonian dimension must match psi")

    propagator = torch.matrix_exp((-1j * float(dt) / float(hbar)) * h_complex)
    return propagator @ psi_complex


def density_matrix(psi: torch.Tensor) -> torch.Tensor:
    """Return the normalized pure-state density matrix ``|psi><psi|``."""
    if psi.ndim != 1:
        raise ValueError("psi must be a one-dimensional state vector")
    psi_complex = _as_complex(psi)
    if not bool(torch.isfinite(psi_complex).all().item()):
        raise ValueError("psi must contain only finite values")
    norm_sq = torch.vdot(psi_complex, psi_complex).real
    if float(norm_sq.item()) <= 0.0:
        raise ValueError("psi must have nonzero norm")
    normalized = psi_complex / torch.sqrt(norm_sq)
    return normalized[:, None] @ normalized.conj()[None, :]


def check_density_matrix(rho: torch.Tensor, tol: float = 1e-6) -> bool:
    """Check square shape, finiteness, Hermiticity, unit trace, and positivity."""
    if not isinstance(rho, torch.Tensor):
        return False
    if rho.ndim != 2 or rho.shape[0] != rho.shape[1]:
        return False
    rho_complex = _as_complex(rho)
    if not bool(torch.isfinite(rho_complex).all().item()):
        return False
    if not torch.allclose(
        rho_complex,
        _adjoint(rho_complex),
        atol=tol,
        rtol=tol,
    ):
        return False
    trace = torch.trace(rho_complex)
    trace_target = torch.ones((), dtype=trace.dtype, device=trace.device)
    if not torch.allclose(trace, trace_target, atol=tol, rtol=tol):
        return False
    eigenvalues = torch.linalg.eigvalsh(
        0.5 * (rho_complex + _adjoint(rho_complex))
    )
    return bool((eigenvalues >= -tol).all().item())


def born_probabilities(state: torch.Tensor, *, validation_tol: float = 1e-6) -> torch.Tensor:
    """Return computational-basis Born probabilities.

    ``state`` may be a state vector or a normalized physical density matrix.
    State vectors are normalized before readout.
    """
    if state.ndim == 1:
        state_complex = _as_complex(state)
        if not bool(torch.isfinite(state_complex).all().item()):
            raise ValueError("state must contain only finite values")
        probabilities = state_complex.abs().square().real
        total = probabilities.sum()
        if float(total.item()) <= 0.0:
            raise ValueError("state must have nonzero norm")
        return probabilities / total

    if state.ndim == 2:
        if not check_density_matrix(state, tol=validation_tol):
            raise ValueError("state must be a physical density matrix")
        rho = _as_complex(state)
        probabilities = torch.diagonal(rho).real.clamp_min(0.0)
        return probabilities / probabilities.sum()

    raise ValueError("state must be a vector or square density matrix")


def sample_born(
    state: torch.Tensor,
    shots: int,
    *,
    seed: int = 0,
) -> torch.Tensor:
    """Sample computational-basis outcomes with an isolated deterministic seed.

    Samples are returned on CPU so the local generator does not mutate global
    Torch RNG state and repeated calls with the same seed are reproducible.
    """
    if isinstance(shots, bool) or not isinstance(shots, int) or shots <= 0:
        raise ValueError("shots must be a positive integer")
    probabilities = born_probabilities(state).detach().to(
        device="cpu",
        dtype=torch.float64,
    )
    generator = torch.Generator(device="cpu")
    generator.manual_seed(int(seed))
    return torch.multinomial(
        probabilities,
        num_samples=shots,
        replacement=True,
        generator=generator,
    )


def lindblad_rhs(
    rho: torch.Tensor,
    hamiltonian: torch.Tensor,
    jump_operators: Sequence[torch.Tensor] = (),
    *,
    rates: Sequence[float] | None = None,
    hbar: float = 1.0,
    hermitian_atol: float = 1e-7,
) -> torch.Tensor:
    """Evaluate the standard finite-dimensional GKSL/Lindblad generator.

    ``d rho / dt = -i[H,rho]/hbar + sum_k rate_k D[L_k](rho)``.
    This is a baseline reference, not a CE-specific dissipator.
    """
    if not math.isfinite(float(hbar)) or hbar <= 0.0:
        raise ValueError("hbar must be finite and positive")
    _validate_square(rho, name="rho")
    _validate_square(hamiltonian, name="hamiltonian")
    if rho.shape != hamiltonian.shape:
        raise ValueError("rho and hamiltonian must have the same shape")

    jumps = tuple(jump_operators)
    rate_values = tuple(1.0 for _ in jumps) if rates is None else tuple(rates)
    if len(rate_values) != len(jumps):
        raise ValueError("rates must match jump_operators")
    if any(not math.isfinite(float(rate)) or rate < 0.0 for rate in rate_values):
        raise ValueError("Lindblad rates must be finite and nonnegative")
    for jump in jumps:
        _validate_square(jump, name="jump operator")
        if jump.shape != rho.shape:
            raise ValueError("jump operator dimension must match rho")

    dtype = _complex_dtype(rho, hamiltonian, *jumps)
    rho_complex = _as_complex(rho, dtype=dtype)
    h_complex = _as_complex(
        hamiltonian,
        dtype=dtype,
        device=rho_complex.device,
    )
    _validate_hermitian(
        h_complex,
        name="hamiltonian",
        atol=hermitian_atol,
    )
    jump_complex = tuple(
        _as_complex(jump, dtype=dtype, device=rho_complex.device)
        for jump in jumps
    )

    derivative = (-1j / float(hbar)) * (
        h_complex @ rho_complex - rho_complex @ h_complex
    )
    for rate, jump in zip(rate_values, jump_complex):
        jump_adjoint = _adjoint(jump)
        gram = jump_adjoint @ jump
        derivative = derivative + float(rate) * (
            jump @ rho_complex @ jump_adjoint
            - 0.5 * (gram @ rho_complex + rho_complex @ gram)
        )
    return derivative


def lindblad_step(
    rho: torch.Tensor,
    hamiltonian: torch.Tensor,
    dt: float,
    jump_operators: Sequence[torch.Tensor] = (),
    *,
    rates: Sequence[float] | None = None,
    hbar: float = 1.0,
    validation_tol: float = 1e-6,
) -> torch.Tensor:
    """Apply the time-independent Lindblad semigroup on a small density matrix.

    The generator is represented on matrix space and exponentiated, avoiding
    the positivity failures of a forward-Euler update.  This is intended as a
    correctness reference for small systems, not as a high-performance solver.
    For nonnegative rates the exact semigroup is CPTP; numerical invariants can
    be checked with :func:`check_density_matrix`.
    """
    if not math.isfinite(float(dt)) or dt < 0.0:
        raise ValueError("dt must be finite and nonnegative")
    if not check_density_matrix(rho, tol=validation_tol):
        raise ValueError("rho must be a physical density matrix")

    jumps = tuple(jump_operators)
    dtype = _complex_dtype(rho, hamiltonian, *jumps)
    rho_complex = _as_complex(rho, dtype=dtype)
    h_complex = _as_complex(
        hamiltonian,
        dtype=dtype,
        device=rho_complex.device,
    )
    jump_complex = tuple(
        _as_complex(jump, dtype=dtype, device=rho_complex.device)
        for jump in jumps
    )
    if dt == 0.0:
        return rho_complex.clone()

    dimension = rho_complex.shape[0]
    generator_columns = []
    for index in range(dimension * dimension):
        basis = torch.zeros_like(rho_complex)
        basis.reshape(-1)[index] = 1.0
        generator_columns.append(
            lindblad_rhs(
                basis,
                h_complex,
                jump_complex,
                rates=rates,
                hbar=hbar,
            ).reshape(-1)
        )
    generator = torch.stack(generator_columns, dim=1)
    channel = torch.matrix_exp(float(dt) * generator)
    return (channel @ rho_complex.reshape(-1)).reshape_as(rho_complex)


def wick_rotate(
    psi: torch.Tensor,
    energy: float,
    dt: float = 0.01,
) -> torch.Tensor:
    """Euclidean rotation t -> -i*tau: exp(-E*dt) * psi (real damping)."""
    if psi.is_complex():
        return psi * torch.exp(torch.tensor(-energy * dt))
    return psi * torch.exp(torch.tensor(-energy * dt))


def quantum_to_real(psi: torch.Tensor) -> torch.Tensor:
    """Project complex state to real for classical relaxation."""
    if psi.is_complex():
        return psi.real
    return psi


def check_norm_conservation(psi_before: torch.Tensor, psi_after: torch.Tensor, tol: float = 1e-6) -> bool:
    """Verify unitary evolution preserves norm."""
    norm_before = psi_before.abs().norm()
    norm_after = psi_after.abs().norm()
    return bool(torch.abs(norm_before - norm_after).item() < tol)


def convergence_inequality(
    grad_norm: float,
    c_k: float,
    phi_norm: float,
    alpha_b: float = ALPHA_B_DEFAULT,
) -> bool:
    """Pointwise sufficient condition: ||grad E|| > C_k * ||phi|| / alpha_b.

    Reference: docs/7_AGI/12_Equation.md 4.7 (gate F2). Scope: pointwise
    monotone-energy region; not a global convergence guarantee.
    """
    return grad_norm > c_k * phi_norm / alpha_b


def time_curvature(m_history: Sequence[torch.Tensor]) -> float:
    """C_k = ||m_k - 2 m_{k-1} + m_{k-2}|| (docs/7_AGI/12_Equation.md 1.5).

    Returns 0.0 when fewer than 3 samples are available.
    """
    if len(m_history) < 3:
        return 0.0
    m_k, m_km1, m_km2 = m_history[-1], m_history[-2], m_history[-3]
    return float((m_k - 2.0 * m_km1 + m_km2).norm().item())


def estimate_mu(
    residuals: Sequence[float],
    *,
    dt_over_tau: float,
    skip: int = 0,
) -> float:
    """Estimate local Hessian floor mu from observed residual contraction.

    Near an attractor, the gradient flow gives
        ||m_{k+1} - m*|| approx (1 - mu * dt/tau) * ||m_k - m*||,
    so a least-squares fit on log residuals returns
        mu approx (1 - mean(r_{k+1}/r_k)) * tau / dt.

    Args:
        residuals: sequence of ||m_k - m*|| values (must be > 0).
        dt_over_tau: integration step ratio dt/tau used by `relax`.
        skip: optional warm-up steps to drop from the head of the sequence.

    Returns:
        mu estimate. Returns 0.0 if the sequence is too short or expanding.
    """
    if dt_over_tau <= 0.0:
        raise ValueError("dt_over_tau must be positive")
    seq = [float(r) for r in residuals[skip:] if r > 0.0]
    if len(seq) < 3:
        return 0.0
    log_ratios = []
    for prev, curr in zip(seq[:-1], seq[1:]):
        ratio = curr / prev
        if ratio <= 0.0 or ratio >= 1.0:
            continue
        log_ratios.append(math.log(ratio))
    if not log_ratios:
        return 0.0
    contraction = math.exp(sum(log_ratios) / len(log_ratios))
    mu = (1.0 - contraction) / dt_over_tau
    return max(mu, 0.0)


def iss_ball_radius(
    *,
    c_k_max: float,
    phi_inf_norm: float,
    mu: float,
    alpha_b: float = ALPHA_B_DEFAULT,
) -> float:
    """ISS ball radius for the bypass-driven memory dynamics (gate F2).

    Reference: docs/7_AGI/12_Equation.md appendix A.1. With dm/dt =
    -nabla_m E / tau + d(t) and ||d||_inf <= C_k_max * ||phi||_inf / (tau * alpha_b),
    the Hessian floor mu yields the closed-form bound

        limsup ||m - m*|| <= C_k_max * ||phi||_inf / (mu * alpha_b).

    Args:
        c_k_max: empirical maximum of trajectory time-curvature C_k.
        phi_inf_norm: empirical sup-norm of the residue field phi.
        mu: local Hessian floor (use `estimate_mu` from contraction history).
        alpha_b: bypass denominator e^{1/3} pi^{1/3}.

    Returns:
        ISS ball radius. Returns +inf if mu == 0.
    """
    if mu <= 0.0:
        return float("inf")
    return c_k_max * phi_inf_norm / (mu * alpha_b)


def pci_regression(
    stability: Sequence[float],
    pci: Sequence[float],
) -> dict:
    """OLS regression PCI ~ alpha * stability + beta (gate F4, A.4).

    Returns alpha, beta, R^2, sample count and Pearson r. With less than 3
    samples or zero stability variance, returns NaNs and zero R^2 so callers
    can detect insufficient data without exception handling.

    Stability is the metacognitive scalar exp(-c_d * d_tau); see
    reality_stone.clarus.agent.ConsciousnessMonitor and 12_Equation.md A.4.
    """
    xs = [float(v) for v in stability]
    ys = [float(v) for v in pci]
    n = min(len(xs), len(ys))
    if n < 3:
        return {"n": n, "alpha": float("nan"), "beta": float("nan"), "r2": 0.0, "pearson_r": float("nan")}
    xs = xs[:n]
    ys = ys[:n]
    mean_x = sum(xs) / n
    mean_y = sum(ys) / n
    sx2 = sum((x - mean_x) ** 2 for x in xs)
    sy2 = sum((y - mean_y) ** 2 for y in ys)
    sxy = sum((x - mean_x) * (y - mean_y) for x, y in zip(xs, ys))
    if sx2 <= 0.0:
        return {"n": n, "alpha": float("nan"), "beta": float("nan"), "r2": 0.0, "pearson_r": float("nan")}
    alpha = sxy / sx2
    beta = mean_y - alpha * mean_x
    r2 = (sxy * sxy) / (sx2 * sy2) if sy2 > 0.0 else 0.0
    pearson_r = sxy / math.sqrt(sx2 * sy2) if sy2 > 0.0 else float("nan")
    return {"n": n, "alpha": alpha, "beta": beta, "r2": r2, "pearson_r": pearson_r}


def iss_report(
    m_history: Sequence[torch.Tensor],
    phi: torch.Tensor,
    *,
    dt_over_tau: float,
    m_star: torch.Tensor | None = None,
    alpha_b: float = ALPHA_B_DEFAULT,
) -> dict:
    """End-to-end gate F2 measurement from a relaxation trajectory.

    Args:
        m_history: list of m_k tensors recorded during `relax`.
        phi: residue field tensor at end of relaxation (or any reference point).
        dt_over_tau: integrator step ratio.
        m_star: optional fixed point estimate. Defaults to mean of last
            quarter of the trajectory.
        alpha_b: bypass denominator.

    Returns:
        Dict with `c_k_max`, `phi_inf_norm`, `mu`, `iss_ball_radius`,
        `residuals`, `samples`. Suitable for direct logging.
    """
    if not m_history:
        return {
            "samples": 0,
            "c_k_max": 0.0,
            "phi_inf_norm": 0.0,
            "mu": 0.0,
            "iss_ball_radius": float("inf"),
        }

    if m_star is None:
        tail = m_history[max(1, 3 * len(m_history) // 4):]
        if not tail:
            tail = m_history[-1:]
        m_star = torch.stack(list(tail)).mean(dim=0)

    residuals = [float((m_k - m_star).norm().item()) for m_k in m_history]
    c_k_max = 0.0
    for k in range(2, len(m_history)):
        c_k = float(
            (m_history[k] - 2.0 * m_history[k - 1] + m_history[k - 2]).norm().item()
        )
        if c_k > c_k_max:
            c_k_max = c_k
    phi_inf_norm = float(phi.detach().abs().max().item())
    mu = estimate_mu(residuals, dt_over_tau=dt_over_tau, skip=0)
    radius = iss_ball_radius(
        c_k_max=c_k_max, phi_inf_norm=phi_inf_norm, mu=mu, alpha_b=alpha_b
    )
    return {
        "samples": len(m_history),
        "c_k_max": c_k_max,
        "phi_inf_norm": phi_inf_norm,
        "mu": mu,
        "iss_ball_radius": radius,
        "residuals": residuals,
    }
